from src.data_reading.base_data_reader import BaseDataReader
from src.data_reading.tuh_data_reader import AnomalyDataReader
from src.data_reading.finger_data_reader import FingerDataReader
from src.data_reading.mnist_data_reader import MnistDataReader
from src.data_reading.wikitext_reader import WikiTextReader
from src.data_reading.adding_problem_reader import AddingProblemReader
from src.data_reading.hgd_data_reader import BBCIDataReader
from src.data_reading.hammerj_data_reader import HammerjDataReader